version: '3'

services:
  init-athena:
    build: 
      context: athena
      dockerfile: Dockerfile
    volumes:
      - ./athena:/app
      - ./data:/app/data
    working_dir: /app
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - S3_DATA_DIR=${S3_DATA_DIR}
    - S3_STAGING_DIR=${S3_STAGING_DIR}
    - USER_ID=${USER_ID}

