version: '3'

services:
  create-db:
    build: 
      context: athena
      dockerfile: Dockerfile
    volumes:
      - ./athena:/app
      - ./data:/app/data
    working_dir: /app
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - S3_BUCKET_BASE=${S3_BUCKET_BASE}
    - S3_OUTPUT_LOCATION=${S3_OUTPUT_LOCATION}
    - USER_ID=${USER_ID}

